'''

This Code computes Cohen's Kappa Score to determine Inter-annotator agrrement between Political Leaning labellings by Expert 1 and Expert 2.
Date: 22 May 2020

'''

# Necessary Imports
from sklearn.metrics import cohen_kappa_score

# Code to convert categorical attributes to numeric.
def labels_to_numeric_categories(l):
	new_l = []

	for item in l:
		if item == "#N/A":
			new_l.append(0)
		elif item == "LEFT_TO_LEFTCENTRE":
			new_l.append(1)
		elif item == "CENTRIST_AND_LEASTBIASED":
			new_l.append(2)
		elif item == "RIGHT_TO_RIGHTCENTRE":
			new_l.append(3)

	return new_l


# Code to get non N/A labels for 2 experts.
def get_labelled_cases(l1, l2):
	temp1 = []
	temp2 = []

	for i in range(len(l1)):
		if l1[i]!=0 and l2[i]!=0:
			temp1.append(l1[i])
			temp2.append(l2[i])

	return temp1, temp2

# Leaning Categories
# 0 = #N/A (Undeterminable Leaning)
# 1 = LEFT_TO_LEFTCENTRE (Left + Left-Centre)
# 2 = CENTRIST_AND_LEASTBIASED (Centrist + Least-Biased)
# 3 = RIGHT_TO_RIGHTCENTRE (Right + Right-Centre)

# Here we have added leaning labels of both the experts for our 123 websites in the order they are mentioned in master sheet

# Expert 1:
expert1 = ["RIGHT_TO_RIGHTCENTRE","RIGHT_TO_RIGHTCENTRE","#N/A","RIGHT_TO_RIGHTCENTRE","RIGHT_TO_RIGHTCENTRE","RIGHT_TO_RIGHTCENTRE","CENTRIST_AND_LEASTBIASED",
"CENTRIST_AND_LEASTBIASED","CENTRIST_AND_LEASTBIASED","RIGHT_TO_RIGHTCENTRE","CENTRIST_AND_LEASTBIASED","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE",
"RIGHT_TO_RIGHTCENTRE","RIGHT_TO_RIGHTCENTRE","LEFT_TO_LEFTCENTRE","CENTRIST_AND_LEASTBIASED","RIGHT_TO_RIGHTCENTRE","RIGHT_TO_RIGHTCENTRE","#N/A",
"LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE","CENTRIST_AND_LEASTBIASED",
"CENTRIST_AND_LEASTBIASED","LEFT_TO_LEFTCENTRE","CENTRIST_AND_LEASTBIASED","CENTRIST_AND_LEASTBIASED","RIGHT_TO_RIGHTCENTRE","LEFT_TO_LEFTCENTRE",
"LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","#N/A","RIGHT_TO_RIGHTCENTRE","RIGHT_TO_RIGHTCENTRE","CENTRIST_AND_LEASTBIASED",
"LEFT_TO_LEFTCENTRE","CENTRIST_AND_LEASTBIASED","#N/A","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","CENTRIST_AND_LEASTBIASED","RIGHT_TO_RIGHTCENTRE",
"#N/A","CENTRIST_AND_LEASTBIASED","LEFT_TO_LEFTCENTRE","CENTRIST_AND_LEASTBIASED","RIGHT_TO_RIGHTCENTRE","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE",
"RIGHT_TO_RIGHTCENTRE","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","RIGHT_TO_RIGHTCENTRE","RIGHT_TO_RIGHTCENTRE","LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE",
"CENTRIST_AND_LEASTBIASED","LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE",
"CENTRIST_AND_LEASTBIASED","#N/A","RIGHT_TO_RIGHTCENTRE","LEFT_TO_LEFTCENTRE","CENTRIST_AND_LEASTBIASED","LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE",
"RIGHT_TO_RIGHTCENTRE","CENTRIST_AND_LEASTBIASED","CENTRIST_AND_LEASTBIASED","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","#N/A","RIGHT_TO_RIGHTCENTRE",
"CENTRIST_AND_LEASTBIASED","RIGHT_TO_RIGHTCENTRE","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","CENTRIST_AND_LEASTBIASED","#N/A","LEFT_TO_LEFTCENTRE",
"LEFT_TO_LEFTCENTRE","#N/A","#N/A","LEFT_TO_LEFTCENTRE","CENTRIST_AND_LEASTBIASED","RIGHT_TO_RIGHTCENTRE","#N/A","LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE",
"LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","#N/A","#N/A","LEFT_TO_LEFTCENTRE","#N/A","#N/A","#N/A","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","#N/A",
"CENTRIST_AND_LEASTBIASED","LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE","CENTRIST_AND_LEASTBIASED","#N/A","RIGHT_TO_RIGHTCENTRE",
"LEFT_TO_LEFTCENTRE","CENTRIST_AND_LEASTBIASED","CENTRIST_AND_LEASTBIASED","#N/A","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","#N/A"]

# Expert 2:
expert2 = ["#N/A","#N/A","#N/A","#N/A","#N/A","#N/A","CENTRIST_AND_LEASTBIASED","#N/A","#N/A","#N/A","#N/A","LEFT_TO_LEFTCENTRE","#N/A","#N/A","#N/A",
"CENTRIST_AND_LEASTBIASED","CENTRIST_AND_LEASTBIASED","#N/A","#N/A","#N/A","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","#N/A","LEFT_TO_LEFTCENTRE",
"LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE","#N/A","CENTRIST_AND_LEASTBIASED","LEFT_TO_LEFTCENTRE","#N/A","#N/A","#N/A","#N/A","#N/A","#N/A",
"RIGHT_TO_RIGHTCENTRE","#N/A","#N/A","RIGHT_TO_RIGHTCENTRE","#N/A","#N/A","#N/A","#N/A","#N/A","RIGHT_TO_RIGHTCENTRE","#N/A","#N/A","#N/A",
"CENTRIST_AND_LEASTBIASED","LEFT_TO_LEFTCENTRE","#N/A","#N/A","#N/A","RIGHT_TO_RIGHTCENTRE","#N/A","#N/A","#N/A","#N/A","#N/A","#N/A","LEFT_TO_LEFTCENTRE",
"CENTRIST_AND_LEASTBIASED","#N/A","#N/A","#N/A","#N/A","#N/A","RIGHT_TO_RIGHTCENTRE","CENTRIST_AND_LEASTBIASED","#N/A","#N/A","LEFT_TO_LEFTCENTRE",
"CENTRIST_AND_LEASTBIASED","LEFT_TO_LEFTCENTRE","LEFT_TO_LEFTCENTRE","RIGHT_TO_RIGHTCENTRE","CENTRIST_AND_LEASTBIASED","CENTRIST_AND_LEASTBIASED","#N/A",
"#N/A","#N/A","#N/A","CENTRIST_AND_LEASTBIASED","RIGHT_TO_RIGHTCENTRE","#N/A","#N/A","CENTRIST_AND_LEASTBIASED","#N/A","#N/A","LEFT_TO_LEFTCENTRE","#N/A",
"#N/A","LEFT_TO_LEFTCENTRE","#N/A","#N/A","#N/A","#N/A","#N/A","#N/A","RIGHT_TO_RIGHTCENTRE","#N/A","#N/A","LEFT_TO_LEFTCENTRE","#N/A","#N/A","#N/A","#N/A",
"#N/A","#N/A","CENTRIST_AND_LEASTBIASED","LEFT_TO_LEFTCENTRE","#N/A","#N/A","#N/A","#N/A","RIGHT_TO_RIGHTCENTRE","#N/A","CENTRIST_AND_LEASTBIASED","#N/A",
"#N/A","#N/A","#N/A","#N/A"]


print("*****************************************************************************************************************")

num_cat_1 = labels_to_numeric_categories(expert1)
num_cat_2 = labels_to_numeric_categories(expert2)

final_label1, final_label2 = get_labelled_cases(num_cat_1, num_cat_2)

print("Cohen\'s Kappa Score = Considering (Expert1,Expert2) Pairs (Only those Media where Expert1 & Expert2 both have labelled)")
print("Total Media =", len(final_label1))
cks = cohen_kappa_score(final_label1, final_label2)
print("Cohen's Kappa Score =", cks)

print("*****************************************************************************************************************")
